import {
  ClerkLoaded,
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import "tailwindcss/tailwind.css";

const MyApp = ({ Component, pageProps }) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClerkProvider>
        {router.pathname === "/" && <Component {...pageProps} />}
        {router.pathname !== "/" && (
          <>
            <SignedIn>
              <ClerkLoaded>
                <Component {...pageProps} />
              </ClerkLoaded>
            </SignedIn>
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
          </>
        )}
      </ClerkProvider>
    </>
  );
};

export default MyApp;
