import React from "react";
import Head from "next/head";
import Main from "src/components/Main";

const Home = () => {
  console.log("rrr");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  );
};

export default Home;
