import React from "react";
import Head from "next/head";
import Public from "src/components/Public";

const Home = () => {
  return (
    <div className="h-screen w-screen bg-gray-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Public />
    </div>
  );
};

export default Home;
